# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e91bcdeeb24252043698b2230886b4dde2749d19320a88eb718ddee0bf2c693fb28d725d26241b47c93b6de30482e4b80d4ab0b5b01d0dc8e3bff77b6bbfc1de

test:
  secret_key_base: bd5c2d7f1394405d0b34462a33a5dcb129cfcfc40ef448014f03b849369705bf2d68a5bab92050004989ca8480c3bd0d0847b1cd898dd846c6384a644dbc730a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
